### ISSUE TITLE
Startup Problem

### ISSUE THREAD

**Issue by the-navigator** [chaojian-zhang/Somewhere#13]
I just found out abt this and this idea is indeed **revolutionary**, cheers mate!

 thrown exception:

at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by chaojian-zhang** [comment]
Hi the-navigator,

Thanks for your interest in my software! I suppose this is the error page you see? 
![Image 20200915 101802](https://user-images.githubusercontent.com/7077098/93222321-d745dd80-f73c-11ea-9f71-04882cb9df88.png)

Can you give some more details on your system information, and in particular which .Net runtime do you have installed? Also are you trying to run on Windows? You can find about your .Net runtime by opening "Add and Remove Programs" on windows, then search for ".Net".

By all means, please try out latest release, where many bugs and issues are likely fixed: https://github.com/chaojian-zhang/Somewhere/releases/tag/V0.1.0

Thanks.

**Comment by the-navigator** [comment]
Yes, that's the one.

The pc im using runs Windows 8.1, 64 bit

wih a .NET Runtime 4.8 SDK.

**Comment by chaojian-zhang** [comment]
Did you get a chance to try the [latest version](https://github.com/chaojian-zhang/Somewhere/releases/tag/V0.1.0)? Does that solve your problem?

**Comment by the-navigator** [comment]
I did, i think ill inspect my system and installation methods, i might have
missed a few steps.

anyways, goodluck on the project, it's splendid and a very innovative idea!
ill see this later if i run on the same error!

**Comment by chaojian-zhang** [comment]
Please try to install **vc++ Redistributable 2015** if you get a chance: https://www.microsoft.com/en-ca/download/details.aspx?id=48145

Thanks and best!
